name: SMBPower
favicon: null
layout_spectrum: 0.7855896558612585
typography_spectrum: 0.8597704211715609
title: SMBPower - The Foundation for a Sustainable Future
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6596500559244305
  lightness: 0.24932364001870155
  saturation: 0.05041875573806465
  rhythmicContrast: 0.32764985924586654
purpose: []
